### ISSUE TITLE
+1

### ISSUE THREAD

**Issue by jhnns** [craigfrancis/iframe-height#1]
Just wanted to leave a comment that this looks good :+1:.

I do agree that the `seamless` spec was probably too complicated. It's mainly about the problem that the iframe's content should be displayed without scrollbars. In contrast to the discussion at whatwg/html#331 and [here](https://groups.google.com/a/chromium.org/forum/#!msg/blink-dev/8tcNMmWJEwQ/7Z_I8vDrGcAJ), I don't think that this issue is resolved by Shadow DOM as the iframe provides other benefits like its own JS context.

**Comment by craigfrancis** [comment]
Completely agree, for years I've been writing hacky JavaScript to stop scroll bars, while I've been waiting for `seamless`, and I'm kind of glad that `seamless` has now been removed so we can focus on the main problem :-)

I'm going to close this issue, as I don't think I need to make any other changes at the moment, but thanks for the comment.
